version: "3.9"
services:
    mysql:
        image: mariadb:10.8.3
        # Uncomment below when on Mac M1
        platform: linux/amd64
        command: --default-authentication-plugin=mysql_native_password
        restart: no
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
    adminer:
        image: adminer
        restart: no
        ports:
            - 8080:8080
